---
- name: apt updateを実行します
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: GPGキー格納のためのkeyringsフォルダを作成します
  become: yes
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"

- name: Google ChromeリポジトリのGPGキーをシステムに追加します
  become: yes
  ansible.builtin.shell: wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/keyrings/google-chrome.gpg

- name: Google ChromeリポジトリをAPTソースに追加します
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present

- name: Autoで追加されたlistファイルを削除します
  become: yes
  ansible.builtin.file:
    path: /etc/apt/source.list.d/google-chrome.list
    state: absent

- name: apt updateを実行します
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Google Chromeをインストールします
  become: yes
  ansible.builtin.apt:
    name: google-chrome-stable
  changed_when: yes
