---
- name: test
  hosts: local
  roles:
    - role: apt
      tags: apt
    - role: snap
      tags: snap
    - role: google-chrome
      tags: google-chrome
    - role: docker
      tags: docker
    - role: jfrog-cli
      tags: jfrog-cli
    - role: gantsign.git_credential_manager
      tags: git_credential_manager
