---
- name: apt updateを実行します
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: VS Codeのインストールに必要なパッケージをインストールします
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
    state: present

- name: GPGキー格納のためのkeyringsフォルダを作成します
  become: yes
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"

- name: VS CodeリポジトリのGPGキーをシステムに追加します
  become: yes
  ansible.builtin.shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/keyrings/package.microsoft.gpg

- name: VS CodeリポジトリをAPTソースに追加します
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/package.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode.list
    state: present

- name: apt updateを実行します
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: VS Codeをインストールします
  become: yes
  ansible.builtin.apt:
    name: code
  changed_when: yes

- name: listファイル書き換えられるのでmvされたlistファイルを削除します
  become: yes
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/vscode.list.list
    state: absent

- name: VS CodeリポジトリをAPTソースに追加し直します
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/package.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode.list
    state: present
