- name: add_user_to_docker_group
  become: yes
  ansible.builtin.user:
    name: "{{ansible_user_id}}"
    groups: docker
    append: yes

- name: restart_docker_daemon
  become: yes
  ansible.builtin.service:
    name: docker
    state: restarted
