---
# This recipe is available at the following URL
# https://note.com/shift_tech/n/n880f71e8e03b
# 2023/9/24 docker recipe is modified. see https://qiita.com/alkshmir/items/9b1c0cdef06eb327c07d
- name: apt updateを実行します
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Dockerのインストールに必要なパッケージをインストールします
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present

- name: DockerリポジトリのGPGキー格納のためのkeyringsフォルダを作成します
  become: yes
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"

- name: DockerリポジトリのGPGキーをシステムに追加します
  become: yes
  ansible.builtin.get_url:
    url: "https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }}/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: DockerリポジトリをAPTソースに追加します
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: apt updateを実行します
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Dockerをインストールします
  become: yes
  ansible.builtin.apt:
    name: docker-ce
  notify: 
    - add_user_to_docker_group
    - restart_docker_daemon
  changed_when: yes
